"""simulate.traffic_pattern — Purple Team Adversary Emulation.

Generates safe, non-malicious Scapy-based Python scripts that replicate
the network timing, port usage, and payload structure of confirmed
malicious findings.  Used for sensor testing and closed-loop validation.

Inputs:
    * ``aipam.findings.reviewed`` — confirmed findings
    * ``aipam.flow.ir`` — flow context for network parameters

Outputs:
    * ``aipam.simulation.py`` — combined Scapy simulation script
    * ``aipam.simulation.manifest`` — per-finding generation manifest
"""

from __future__ import annotations

import json
import os
import sys
import time
import uuid
from pathlib import Path
from typing import Any, Dict, List, Optional

# ---------------------------------------------------------------------------
# AIPAM import bootstrap
# ---------------------------------------------------------------------------

_AIPAM_BACKEND = os.environ.get(
    "AIPAM_BACKEND_PATH",
    str(Path(__file__).resolve().parents[3] / "AIPAM" / "backend"),
)
if _AIPAM_BACKEND not in sys.path:
    sys.path.insert(0, _AIPAM_BACKEND)


# ---------------------------------------------------------------------------
# Script Generation
# ---------------------------------------------------------------------------

SCRIPT_HEADER = '''#!/usr/bin/env python3
"""AIPAM Purple Team — Adversary Emulation Script (Auto-Generated).

⚠  SAFE DETONATION ONLY — This script generates BENIGN traffic that
   mimics the timing and structure of real malicious network behavior.
   No actual payloads, exploits, or malware are included.

Usage:
    sudo python simulation_script.py [--interface eth0] [--pcap output.pcap]

Requirements:
    pip install scapy

Generated by: AIPAM simulate.traffic_pattern
"""

from __future__ import annotations

import argparse
import random
import sys
import time
from datetime import datetime

try:
    from scapy.all import (
        IP, TCP, UDP, DNS, DNSQR, Raw, Ether,
        send, sendp, wrpcap, conf
    )
except ImportError:
    print("ERROR: scapy is required. Install with: pip install scapy")
    sys.exit(1)


def log(msg: str):
    print(f"[{datetime.now().strftime('%H:%M:%S')}] {msg}")


# Capture all generated packets for PCAP export
GENERATED_PACKETS = []


def capture(pkt):
    """Record a packet for PCAP export."""
    GENERATED_PACKETS.append(pkt)
    return pkt

'''

SCRIPT_FOOTER = '''

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="AIPAM Purple Team Simulation")
    parser.add_argument("--interface", "-i", default=None,
                        help="Network interface to send on (default: loopback)")
    parser.add_argument("--pcap", "-p", default="simulation_capture.pcap",
                        help="Output PCAP file (default: simulation_capture.pcap)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Generate packets but don't send (PCAP only)")
    parser.add_argument("--count", type=int, default=1,
                        help="Number of simulation rounds")
    args = parser.parse_args()

    if args.interface:
        conf.iface = args.interface

    log(f"AIPAM Purple Team Simulation — {len(SIMULATIONS)} scenarios")
    log(f"Mode: {'DRY-RUN (PCAP only)' if args.dry_run else 'LIVE'}")

    for round_num in range(args.count):
        if args.count > 1:
            log(f"\\n=== Round {round_num + 1}/{args.count} ===")

        for sim in SIMULATIONS:
            log(f"\\nRunning: {sim['name']}")
            log(f"  MITRE: {sim['mitre']}")
            log(f"  Description: {sim['description']}")
            try:
                packets = sim["func"](dry_run=args.dry_run)
                log(f"  Generated {len(packets)} packets")
            except Exception as e:
                log(f"  ERROR: {e}")

    # Write PCAP
    if GENERATED_PACKETS:
        wrpcap(args.pcap, GENERATED_PACKETS)
        log(f"\\nPCAP written: {args.pcap} ({len(GENERATED_PACKETS)} packets)")
    else:
        log("\\nNo packets generated.")

    log("Simulation complete.")


if __name__ == "__main__":
    main()
'''


def _generate_simulation_function(
    finding: Dict[str, Any],
    flow_context: Dict[str, Any],
    index: int,
    config: Dict[str, Any],
) -> str:
    """Generate a Scapy simulation function from a finding.

    Uses LLM if available, falls back to deterministic template.
    """
    mitre = finding.get("mitre_technique_id", "T0000")
    severity = finding.get("severity", "medium")
    evidence = finding.get("raw_evidence_snippet", finding.get("evidence_snippet",
               finding.get("description", "")))
    classification = finding.get("classification", "")
    hosts = finding.get("affected_hosts", [])
    cited_flows = finding.get("cited_flow_ids", [])

    # Extract network parameters from flow context
    src_ip = "10.0.0.100"
    dst_ip = "185.220.101.42"
    dst_port = 443
    proto = "tcp"

    for flow in flow_context.get("flows", []):
        if flow.get("flow_id") in cited_flows:
            src_ip = flow.get("src_ip", src_ip)
            dst_ip = flow.get("dst_ip", dst_ip)
            dst_port = flow.get("dst_port", dst_port)
            proto = flow.get("proto", proto)
            break

    # Try LLM generation
    llm_code = _call_llm_for_script(finding, src_ip, dst_ip, dst_port, proto, config)
    if llm_code:
        return llm_code

    # Fallback: deterministic template based on MITRE technique
    return _template_simulation(
        index=index,
        mitre=mitre,
        classification=classification,
        evidence=evidence,
        src_ip=src_ip,
        dst_ip=dst_ip,
        dst_port=dst_port,
        proto=proto,
    )


def _call_llm_for_script(
    finding: Dict[str, Any],
    src_ip: str, dst_ip: str, dst_port: int, proto: str,
    config: Dict[str, Any],
) -> Optional[str]:
    """Ask the LLM to generate a simulation function."""
    try:
        import httpx
    except ImportError:
        return None

    endpoint = config.get("llm_endpoint", "http://localhost:11434")
    model = config.get("model_name", "llama3.1:8b")

    mitre = finding.get("mitre_technique_id", "")
    evidence = finding.get("raw_evidence_snippet", finding.get("description", ""))
    index = finding.get("_index", 0)

    prompt = f"""Generate a Python function using Scapy that safely emulates this network behavior for security testing:

MITRE ATT&CK: {mitre}
Evidence: {evidence}
Source IP: {src_ip}
Destination IP: {dst_ip}
Destination Port: {dst_port}
Protocol: {proto}

Requirements:
- Function name: simulate_{index}(dry_run=False)
- Use Scapy (IP, TCP, UDP, DNS, Raw, send)
- SAFE: No real payloads or exploits. Use benign data that mimics timing/structure.
- Call capture(pkt) on each packet before sending
- Return list of generated packets
- Add realistic timing delays with time.sleep()
- Include comments explaining what each section emulates
- If dry_run=True, generate packets but don't call send()

Return ONLY the Python function code, no markdown or explanation."""

    try:
        with httpx.Client(timeout=30.0) as client:
            resp = client.post(
                f"{endpoint}/api/generate",
                json={"model": model, "prompt": prompt, "stream": False},
            )
            if resp.status_code == 200:
                body = resp.json()
                code = body.get("response", "")
                # Validate it looks like Python
                if "def simulate_" in code and "scapy" in code.lower():
                    return code.strip()
    except Exception:
        pass
    return None


def _template_simulation(
    index: int,
    mitre: str,
    classification: str,
    evidence: str,
    src_ip: str,
    dst_ip: str,
    dst_port: int,
    proto: str,
) -> str:
    """Generate a deterministic Scapy simulation function from template."""

    safe_evidence = evidence.replace('"', '\\"').replace("'", "\\'")[:200]
    func_name = f"simulate_{index}"

    # Map MITRE techniques to simulation patterns
    if mitre.startswith("T1071"):  # Application Layer Protocol (C2)
        return f'''
def {func_name}(dry_run=False):
    """Simulate: {mitre} — C2 Beacon Pattern
    Classification: {classification}
    Evidence: {safe_evidence}
    """
    packets = []
    log("  Emulating C2 beacon pattern ({mitre})")

    for i in range(5):
        # TLS-like handshake to suspicious destination
        syn = capture(IP(src="{src_ip}", dst="{dst_ip}") /
                      TCP(sport=random.randint(49152, 65535), dport={dst_port},
                          flags="S"))
        packets.append(syn)

        # Simulated beacon payload (benign)
        data = capture(IP(src="{src_ip}", dst="{dst_ip}") /
                       TCP(sport=random.randint(49152, 65535), dport={dst_port},
                           flags="PA") /
                       Raw(load=b"AIPAM-SAFE-BEACON-" + str(i).encode()))
        packets.append(data)

        if not dry_run:
            send(syn, verbose=0)
            send(data, verbose=0)

        # Realistic beacon interval (jittered)
        time.sleep(random.uniform(0.5, 1.5))

    return packets
'''

    elif mitre.startswith("T1059"):  # Command and Scripting Interpreter
        return f'''
def {func_name}(dry_run=False):
    """Simulate: {mitre} — Encoded Command Execution Pattern
    Classification: {classification}
    Evidence: {safe_evidence}
    """
    packets = []
    log("  Emulating encoded command execution ({mitre})")

    # Simulate HTTP POST with encoded payload (benign content)
    for i in range(3):
        import base64
        safe_payload = base64.b64encode(b"AIPAM-SAFE-SIMULATION-PAYLOAD").decode()

        pkt = capture(IP(src="{src_ip}", dst="{dst_ip}") /
                      TCP(sport=random.randint(49152, 65535), dport=80,
                          flags="PA") /
                      Raw(load=f"POST /api HTTP/1.1\\r\\nContent-Type: application/octet-stream\\r\\n\\r\\n{{safe_payload}}".encode()))
        packets.append(pkt)

        if not dry_run:
            send(pkt, verbose=0)
        time.sleep(random.uniform(0.3, 0.8))

    return packets
'''

    elif mitre.startswith("T1027"):  # Obfuscated Files or Information
        return f'''
def {func_name}(dry_run=False):
    """Simulate: {mitre} — Obfuscated Data Transfer
    Classification: {classification}
    Evidence: {safe_evidence}
    """
    packets = []
    log("  Emulating obfuscated data transfer ({mitre})")

    for i in range(4):
        # XOR-like payload structure (benign)
        payload = bytes([b ^ 0x42 for b in b"AIPAM-SAFE-OBFUSCATED-DATA"])

        pkt = capture(IP(src="{src_ip}", dst="{dst_ip}") /
                      TCP(sport=random.randint(49152, 65535), dport={dst_port},
                          flags="PA") /
                      Raw(load=payload))
        packets.append(pkt)

        if not dry_run:
            send(pkt, verbose=0)
        time.sleep(random.uniform(0.2, 0.6))

    return packets
'''

    elif mitre.startswith("T1055"):  # Process Injection
        return f'''
def {func_name}(dry_run=False):
    """Simulate: {mitre} — Lateral Movement / Injection Pattern
    Classification: {classification}
    Evidence: {safe_evidence}
    """
    packets = []
    log("  Emulating lateral movement pattern ({mitre})")

    # SMB-like connection to internal host
    for i in range(3):
        pkt = capture(IP(src="{src_ip}", dst="{dst_ip}") /
                      TCP(sport=random.randint(49152, 65535), dport=445,
                          flags="PA") /
                      Raw(load=b"\\xffSMB-AIPAM-SAFE-SIMULATION"))
        packets.append(pkt)

        if not dry_run:
            send(pkt, verbose=0)
        time.sleep(random.uniform(0.1, 0.4))

    return packets
'''

    elif mitre.startswith("T1048") or mitre.startswith("T1041"):  # Exfiltration
        return f'''
def {func_name}(dry_run=False):
    """Simulate: {mitre} — Data Exfiltration Pattern
    Classification: {classification}
    Evidence: {safe_evidence}
    """
    packets = []
    log("  Emulating data exfiltration ({mitre})")

    # DNS tunneling pattern (benign queries)
    for i in range(6):
        import base64
        subdomain = base64.b32encode(f"safe-data-chunk-{{i}}".encode()).decode().rstrip("=").lower()
        query = f"{{subdomain}}.aipam-safe.test"

        pkt = capture(IP(src="{src_ip}", dst="8.8.8.8") /
                      UDP(sport=random.randint(49152, 65535), dport=53) /
                      DNS(rd=1, qd=DNSQR(qname=query)))
        packets.append(pkt)

        if not dry_run:
            send(pkt, verbose=0)
        time.sleep(random.uniform(0.3, 1.0))

    return packets
'''

    else:  # Generic catch-all
        return f'''
def {func_name}(dry_run=False):
    """Simulate: {mitre} — Generic Network Pattern
    Classification: {classification}
    Evidence: {safe_evidence}
    """
    packets = []
    log("  Emulating network pattern ({mitre})")

    for i in range(4):
        pkt = capture(IP(src="{src_ip}", dst="{dst_ip}") /
                      TCP(sport=random.randint(49152, 65535), dport={dst_port},
                          flags="PA") /
                      Raw(load=b"AIPAM-SAFE-GENERIC-" + str(i).encode()))
        packets.append(pkt)

        if not dry_run:
            send(pkt, verbose=0)
        time.sleep(random.uniform(0.3, 0.8))

    return packets
'''


# ---------------------------------------------------------------------------
# DAWN entry point
# ---------------------------------------------------------------------------

def run(context: Dict[str, Any], link_config: Dict[str, Any]) -> Dict[str, Any]:
    """
    DAWN Link: simulate.traffic_pattern

    1. Load confirmed findings + flow IR
    2. For each finding, generate a Scapy simulation function
    3. Assemble into a runnable script
    4. Publish aipam.simulation.py + manifest
    """
    project_id = context["project_id"]
    pipeline_id = context.get("pipeline_id", "aipam_forensic")
    artifact_store = context["artifact_store"]
    sandbox = context["sandbox"]
    ledger = context["ledger"]
    run_id = context.get("run_id", str(uuid.uuid4()))

    config = link_config.get("spec", {}).get("config", {})

    print(f"[simulate.traffic_pattern] Generating adversary emulation for {project_id}")

    start_time = time.time()

    # ── Load artifacts ────────────────────────────────────────────────
    findings_meta = artifact_store.get("aipam.findings.reviewed")
    if not findings_meta:
        # Fall back to unreviewed findings
        findings_meta = artifact_store.get("aipam.findings.ir")
    if not findings_meta:
        print("  ⚠ No findings available — skipping simulation generation")
        return {"status": "SUCCEEDED", "metrics": {"skipped": True, "reason": "no findings"}}

    with open(findings_meta["path"]) as f:
        findings_data = json.load(f)

    flow_meta = artifact_store.get("aipam.flow.ir")
    flow_ir = {}
    if flow_meta:
        with open(flow_meta["path"]) as f:
            flow_ir = json.load(f)

    findings = findings_data.get("findings", [])
    # Filter to confirmed only
    confirmed = [f for f in findings if not f.get("requires_review", False)]
    max_findings = config.get("max_findings", 10)
    confirmed = confirmed[:max_findings]

    print(f"  Confirmed findings: {len(confirmed)}")

    if not confirmed:
        print("  ⚠ No confirmed findings — generating empty script")
        confirmed = findings[:max_findings]  # Use all if none confirmed

    # ── Generate simulation functions ─────────────────────────────────
    functions = []
    manifest_entries = []

    for i, finding in enumerate(confirmed):
        finding["_index"] = i
        func_code = _generate_simulation_function(finding, flow_ir, i, config)
        functions.append(func_code)

        manifest_entries.append({
            "index": i,
            "mitre_technique_id": finding.get("mitre_technique_id", ""),
            "severity": finding.get("severity", ""),
            "classification": finding.get("classification", ""),
            "description": finding.get("description", finding.get("rationale", ""))[:200],
            "function_name": f"simulate_{i}",
        })

    # ── Assemble script ───────────────────────────────────────────────
    sim_registry = "\n\nSIMULATIONS = [\n"
    for entry in manifest_entries:
        sim_registry += (
            f'    {{"name": "{entry["function_name"]}", '
            f'"mitre": "{entry["mitre_technique_id"]}", '
            f'"description": "{entry["description"][:80]}", '
            f'"func": {entry["function_name"]}}},\n'
        )
    sim_registry += "]\n"

    full_script = SCRIPT_HEADER + "\n".join(functions) + sim_registry + SCRIPT_FOOTER

    duration_ms = int((time.time() - start_time) * 1000)

    # ── Publish ───────────────────────────────────────────────────────
    sandbox.publish(
        artifact="aipam.simulation.py",
        filename="simulation_script.py",
        obj=full_script,
        schema="text",
    )

    manifest = {
        "project_id": project_id,
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "total_simulations": len(manifest_entries),
        "findings_source": "aipam.findings.reviewed",
        "safe_mode": config.get("safe_mode", True),
        "simulations": manifest_entries,
        "duration_ms": duration_ms,
    }
    sandbox.publish(
        artifact="aipam.simulation.manifest",
        filename="simulation_manifest.json",
        obj=manifest,
        schema="json",
    )

    # ── Audit ─────────────────────────────────────────────────────────
    ledger.log_event(
        project_id=project_id, pipeline_id=pipeline_id,
        link_id="simulate.traffic_pattern", run_id=run_id,
        step_id="simulation_generated", status="OK",
        inputs={"confirmed_findings": len(confirmed)},
        outputs={"simulations": len(manifest_entries)},
        metrics={"duration_ms": duration_ms, "simulations": len(manifest_entries)},
        errors={},
    )

    print(f"[simulate.traffic_pattern] ✓ {len(manifest_entries)} simulations generated "
          f"({len(full_script)} chars) in {duration_ms}ms")

    return {
        "status": "SUCCEEDED",
        "metrics": {
            "duration_ms": duration_ms,
            "simulations": len(manifest_entries),
            "script_length": len(full_script),
        },
    }
